import Container from '@/components/container';
import Header from '@/components/layout/header/header';
import Footer from '@/components/root/main/footer';
import { authOptions } from '@/lib/auth';
import type { Metadata } from 'next';
import { getServerSession } from 'next-auth';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession(authOptions);

  return (
    <Container>
      <Header session={session} />
      {children}
      <Footer />
    </Container>
  );
}
