import type { Metadata } from 'next';
import { Manrope } from 'next/font/google';
import localFont from 'next/font/local';
import './globals.css';
import RootProviders from '@/components/Providers/root-providers';
import Header from '@/components/header/header';
import Container from '@/components/container';
import { getServerSession } from 'next-auth';

const manrope = Manrope({
  subsets: ['latin', 'cyrillic'],
  variable: '--font-manrope',

  display: 'swap',
  weight: ['400', '500', '600', '700', '800'],
});

const satoshi = localFont({
  src: [
    {
      path: '../public/fonts/Satoshi/Satoshi-Regular.woff2',
      weight: '400',
      style: 'normal',
    },
    {
      path: '../public/fonts/Satoshi/Satoshi-Medium.woff2',
      weight: '500',
      style: 'normal',
    },
    {
      path: '../public/fonts/Satoshi/Satoshi-Bold.woff2',
      weight: '700',
      style: 'normal',
    },
  ],
  variable: '--font-satoshi',
  display: 'swap',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession();
  return (
    <html lang="en">
      <body className={`${satoshi.variable} ${manrope.variable}`}>
        <Container>
          <Header session={session} />
          <RootProviders>{children}</RootProviders>{' '}
        </Container>
      </body>
    </html>
  );
}
